stages:
  - deploy

deploy_flask_app:
  stage: deploy
  script:
    # Update and install dependencies
    - sudo apt-get update && sudo apt-get install -y python3-venv python3-pip

    # Navigate to the project directory
    - cd $CI_PROJECT_DIR

    # Check Python and pip versions
    - python3 --version
    - pip --version

    # Set up a Python virtual environment
    - python3 -m venv venv
    - source venv/bin/activate

    #Check if virtual environment is activated
    - which python
    - which pip

    # Install dependencies
    - pip install -r requirements.txt

    # Initialize the database
    - python3 create_db.py || echo "Database initialization skipped"

    # Stop any running Flask app 
    - pkill -f "flask run" || true

    # Start the Flask app
    - nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &

  tags:
    - deploy
    - production
    - website

  only:
    - main
